import type { ReactNode } from "react";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { FinancialAccountsCard } from "./financial-accounts-card";
import { ApiError } from "@/lib/api";
import { getSiteText } from "@/lib/site";

const {
  cacheStore,
  createFinancialAccountMock,
  deleteFinancialAccountMock,
  getFinancialAccountsMock,
  invalidateCacheKeyMock,
  toastErrorMock,
  toastSuccessMock,
  updateFinancialAccountMock,
} = vi.hoisted(() => ({
  cacheStore: new Map<string, unknown>(),
  createFinancialAccountMock: vi.fn(),
  deleteFinancialAccountMock: vi.fn(),
  getFinancialAccountsMock: vi.fn(),
  invalidateCacheKeyMock: vi.fn(),
  toastErrorMock: vi.fn(),
  toastSuccessMock: vi.fn(),
  updateFinancialAccountMock: vi.fn(),
}));

vi.mock("@/lib/api", () => ({
  ApiError: class ApiError extends Error {
    constructor(
      public status: number,
      message: string,
    ) {
      super(message);
    }
  },
  api: {
    getFinancialAccounts: getFinancialAccountsMock,
    createFinancialAccount: createFinancialAccountMock,
    updateFinancialAccount: updateFinancialAccountMock,
    deleteFinancialAccount: deleteFinancialAccountMock,
  },
}));

vi.mock("@/components/providers/site-preferences-provider", () => ({
  useSitePreferences: () => ({
    site: getSiteText("es"),
  }),
}));

vi.mock("@/lib/cache", () => ({
  cacheKeys: {
    financialAccounts: "cache:financial-accounts",
  },
  cacheTtls: {
    financialAccounts: 60_000,
  },
  getCache: (key: string) => cacheStore.get(key) ?? null,
  setCache: (key: string, value: unknown) => {
    cacheStore.set(key, value);
  },
  invalidateCacheKey: invalidateCacheKeyMock,
  subscribeToCacheKeys: () => () => {},
}));

vi.mock("sonner", () => ({
  toast: {
    error: toastErrorMock,
    success: toastSuccessMock,
  },
}));

vi.mock("@/components/ui/dialog", () => ({
  Dialog: ({
    children,
    open,
  }: {
    children: ReactNode;
    open: boolean;
  }) => (open ? <div>{children}</div> : null),
  DialogContent: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogDescription: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogFooter: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogHeader: ({ children }: { children: ReactNode }) => <div>{children}</div>,
  DialogTitle: ({ children }: { children: ReactNode }) => <div>{children}</div>,
}));

describe("FinancialAccountsCard", () => {
  beforeEach(() => {
    cacheStore.clear();
    createFinancialAccountMock.mockReset();
    deleteFinancialAccountMock.mockReset();
    getFinancialAccountsMock.mockReset();
    invalidateCacheKeyMock.mockReset();
    toastErrorMock.mockReset();
    toastSuccessMock.mockReset();
    updateFinancialAccountMock.mockReset();

    getFinancialAccountsMock.mockResolvedValue([
      {
        id: "acc-1",
        name: "Main account",
        currency: "COP",
        is_default: true,
        created_at: "2026-03-01T00:00:00Z",
      },
      {
        id: "acc-2",
        name: "Wallet",
        currency: "COP",
        is_default: false,
        created_at: "2026-03-02T00:00:00Z",
      },
    ]);
  });

  afterEach(() => {
    cleanup();
  });

  it("creates a financial account from the dialog", async () => {
    createFinancialAccountMock.mockResolvedValue({
      id: "acc-3",
      name: "Savings",
      currency: "COP",
      is_default: false,
      created_at: "2026-03-03T00:00:00Z",
    });

    render(<FinancialAccountsCard />);

    await screen.findByText("Cuenta principal");
    expect(getFinancialAccountsMock).toHaveBeenCalledTimes(1);
    expect(
      screen.getByRole("button", { name: "Para que sirven las cuentas?" }),
    ).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Agregar cuenta" }));
    fireEvent.change(screen.getByLabelText("Nombre de la cuenta"), {
      target: { value: "Savings" },
    });
    fireEvent.click(screen.getAllByRole("button", { name: "Agregar cuenta" })[1]);

    await waitFor(() => {
      expect(createFinancialAccountMock).toHaveBeenCalledWith({
        name: "Savings",
      });
    });

    expect(toastSuccessMock).toHaveBeenCalledWith("Cuenta creada");
    expect(invalidateCacheKeyMock).toHaveBeenCalledWith(
      "cache:financial-accounts",
    );
  });

  it("localizes the autogenerated default account name in spanish", async () => {
    render(<FinancialAccountsCard />);

    await screen.findByText("Cuenta principal");
    expect(screen.queryByText("Main account")).not.toBeInTheDocument();
  });

  it("sets another account as default from the list", async () => {
    updateFinancialAccountMock.mockResolvedValue({
      id: "acc-2",
      name: "Wallet",
      currency: "COP",
      is_default: true,
      created_at: "2026-03-02T00:00:00Z",
    });

    render(<FinancialAccountsCard />);

    await screen.findByText("Wallet");
    expect(getFinancialAccountsMock).toHaveBeenCalledTimes(1);

    fireEvent.click(screen.getByRole("button", { name: "Usar por defecto" }));

    await waitFor(() => {
      expect(updateFinancialAccountMock).toHaveBeenCalledWith("acc-2", {
        is_default: true,
      });
    });

    expect(toastSuccessMock).toHaveBeenCalledWith(
      "Cuenta por defecto actualizada",
    );
    expect(invalidateCacheKeyMock).toHaveBeenCalledWith(
      "cache:financial-accounts",
    );
  });

  it("localizes delete errors with transaction count", async () => {
    deleteFinancialAccountMock.mockRejectedValue(
      new ApiError(409, "Financial account has 2 transactions"),
    );

    render(<FinancialAccountsCard />);

    await screen.findByText("Wallet");

    fireEvent.click(screen.getAllByRole("button", { name: "Eliminar" })[1]);
    fireEvent.click(screen.getAllByRole("button", { name: "Eliminar" })[2]);

    await waitFor(() => {
      expect(toastErrorMock).toHaveBeenCalledWith(
        "No puedes eliminar esta cuenta porque tiene 2 transacciones.",
      );
    });
  });
});
