export type SiteLocale = "es" | "en";

export const defaultSiteLocale: SiteLocale = "es";
export const siteLocales: SiteLocale[] = ["es", "en"];

export function isSiteLocale(value: string): value is SiteLocale {
  return siteLocales.includes(value as SiteLocale);
}

const mainPageContent = {
  es: {
    seo: {
      title: "Dinerance | Finanzas personales, ingresos y gastos",
      description:
        "Dinerance es una app de finanzas personales para registrar ingresos y gastos con fecha real, organizar movimientos y entender tu balance mensual.",
    },
    header: {
      brand: "Dinerance",
      subtitle: "Finanzas personales",
      dashboard: "Dashboard",
      signIn: "Iniciar sesion",
      logoAlt: "Dinerance",
    },
    hero: {
      badge: "Finanzas personales",
      title: "Controla tus finanzas",
      accent: "con claridad total",
      description: "Ve exactamente en qué se va tu dinero, sin complicaciones.",
      ctaAuthenticated: "Ir al dashboard",
      ctaGuest: "Empieza a controlar tu dinero hoy",
      supporting: "App para ingresos, gastos y balance en un solo lugar.",
      logoAlt: "Logo de Dinerance",
    },
    background: {
      billCode: "DNR",
      billAmounts: ["120", "480", "260", "720", "90"],
      currencySymbol: "$",
    },
  },
  en: {
    seo: {
      title: "Dinerance | Personal finance, income and expenses",
      description:
        "Dinerance is a personal finance app to track income and expenses with real dates, organize transactions, and understand your monthly balance.",
    },
    header: {
      brand: "Dinerance",
      subtitle: "Personal finance",
      dashboard: "Dashboard",
      signIn: "Sign in",
      logoAlt: "Dinerance",
    },
    hero: {
      badge: "Personal finance",
      title: "Control your finances",
      accent: "with total clarity",
      description: "See exactly where your money goes, without the hassle.",
      ctaAuthenticated: "Go to dashboard",
      ctaGuest: "Start managing your money today",
      supporting: "Income, expenses, and balance in one place.",
      logoAlt: "Dinerance logo",
    },
    background: {
      billCode: "DNR",
      billAmounts: ["120", "480", "260", "720", "90"],
      currencySymbol: "$",
    },
  },
} as const;

const siteTexts = {
  es: {
    metadata: {
      title: mainPageContent.es.seo.title,
      description: mainPageContent.es.seo.description,
      htmlLang: "es",
    },
    common: {
      loading: "Cargando...",
      unexpectedError: "Error inesperado",
      mobileTableScrollHint: "Desliza para ver mas columnas.",
      none: "Ninguno",
      all: "Todos",
      clearFilters: "Limpiar filtros",
      refresh: "Actualizar",
      cancel: "Cancelar",
      saveChanges: "Guardar cambios",
      edit: "Editar",
      delete: "Eliminar",
      actions: "Acciones",
      direction: "Direccion",
      category: "Categoria",
      date: "Fecha",
      amount: "Monto",
      currency: "Moneda",
      description: "Descripcion",
      dash: "-",
      income: "Ingreso",
      expense: "Gasto",
    },
    appLayout: {
      mobileMenuTitle: "Menu",
      mobileMenuDescription: "Navega por tu panel y administra tu sesion.",
      nav: {
        balance: "Balance",
        transactions: "Transacciones",
        categories: "Categorias",
        profile: "Perfil",
      },
      signOut: "Cerrar sesion",
    },
    auth: {
      login: {
        title: "Iniciar sesion",
        email: "Correo",
        password: "Contrasena",
        submit: "Iniciar sesion",
        submitting: "Iniciando sesion...",
        google: "Continuar con Google",
        googleSubmitting: "Redirigiendo a Google...",
        orContinueWithEmail: "o sigue con correo",
        noAccount: "No tienes cuenta?",
        register: "Registrate",
        notRegistered: "El usuario no esta registrado.",
        validations: {
          invalidEmail: "Correo invalido",
          passwordRequired: "La contrasena es obligatoria",
        },
        successToast: "Sesion iniciada correctamente",
      },
      register: {
        title: "Crear cuenta",
        name: "Nombre",
        email: "Correo",
        password: "Contrasena",
        confirmPassword: "Confirmar contrasena",
        submit: "Crear cuenta",
        submitting: "Creando cuenta...",
        google: "Registrarse con Google",
        googleSubmitting: "Redirigiendo a Google...",
        orContinueWithEmail: "o crea tu cuenta con correo",
        hasAccount: "Ya tienes cuenta?",
        signIn: "Inicia sesion",
        validations: {
          nameRequired: "El nombre es obligatorio",
          invalidEmail: "Correo invalido",
          passwordMin: "La contrasena debe tener al menos 8 caracteres",
          confirmRequired: "Confirma tu contrasena",
          passwordsDontMatch: "Las contrasenas no coinciden",
        },
        successToast: "Cuenta creada correctamente.",
        profileCreatedToast: "Usuario creado correctamente.",
      },
    },
    pages: {
      main: mainPageContent.es,
      balance: {
        title: "Balance",
        subtitle: "Resumen financiero del mes seleccionado y su historico.",
        heading: (monthLabel: string) => `Resumen financiero - ${monthLabel}`,
        monthLabel: "Mes",
        latestMonthHint:
          "Si no eliges un mes, se muestra el ultimo mes con movimientos.",
        currentCardDescription:
          "Vista consolidada de ingresos, gastos y balance.",
        onboardingTitle: "Empieza a usar tu balance",
        onboardingDescription:
          "Para ver resultados aqui, primero crea una categoria y luego registra una transaccion.",
        onboardingCategoryStepTitle: "Crear una categoria",
        onboardingCategoryStepDescription:
          "Organiza tus ingresos o gastos antes de registrar movimientos.",
        onboardingTransactionStepTitle: "Registrar una transaccion",
        onboardingTransactionStepDescription:
          "Agrega tu primer movimiento para que el balance empiece a calcularse.",
        onboardingCompleted: "Completado",
        onboardingPending: "Pendiente",
        onboardingCategoryPromptTitle: "Tu primer paso",
        onboardingCategoryPromptDescription:
          "Aun no tienes categorias. Crea una para empezar a organizar tus movimientos.",
        onboardingTransactionPromptTitle: "Siguiente paso",
        onboardingTransactionPromptDescription:
          "Ya tienes categorias. Ahora registra tu primera transaccion para ver el balance.",
        historyTitle: "Balance mensual",
        historyDescription: "Todos los meses con movimientos registrados.",
        noHistory: "Todavia no hay movimientos para calcular el balance.",
        selectedMonthEmpty: "No hay movimientos en el mes seleccionado.",
      },
      categories: {
        title: "Categorias",
        subtitle: "Organiza tus transacciones por ingresos y gastos.",
        newCardTitle: "Nueva categoria",
        newCardDescription:
          "Agrega una categoria para agrupar tus movimientos.",
        name: "Nombre",
        direction: "Direccion",
        parentOptional: "Agrupar en (opcional)",
        parentHelpTitle: "Para que sirve?",
        parentHelpDescription:
          "Si eliges un grupo, la nueva categoría creada se convierte en una subcategoría. Esto te ayuda a organizar mejor en qué gastaste tu dinero o de dónde provino, por ejemplo: Grupo: Hogar > Subcategoría: Mercado.",
        namePlaceholder: "Ej: Mercado",
        addCategory: "Agregar categoria",
        create: "Crear categoria",
        creating: "Creando...",
        filters: "Filtros",
        listTitle: "Categorias",
        groupedView: "Agrupadas",
        allView: "Todas",
        uncategorizedGroup: "Sin grupo",
        subcategoryLabel: "Subcategoria",
        unknownParent: "Grupo desconocido",
        subcategoriesCount: (count: number) => `${count} subcategorias`,
        categoriesCount: (count: number) => `${count} categorias`,
        loading: "Cargando...",
        empty: "No se encontraron categorias.",
        editTitle: "Editar categoria",
        save: "Guardar cambios",
        saving: "Guardando...",
        deleteTitle: "Eliminar categoria?",
        deleteDescription: (name: string) =>
          `Seguro que quieres eliminar "${name}"? Esta accion no se puede deshacer.`,
        deleted: "Categoria eliminada",
        created: "Categoria creada",
        updated: "Categoria actualizada",
        duplicateCategory: (name: string) => `Tu categoria ${name} ya existe`,
        groupCannotBecomeSubcategory:
          "No puedes agregar un grupo porque esta categoria ya es un grupo.",
        groupMustBeTopLevel:
          "Solo puedes agrupar dentro de una categoria principal.",
        groupMustMatchDirection:
          "El grupo debe tener la misma direccion que la categoria.",
        groupDirectionCannotChange:
          "No puedes cambiar la direccion de un grupo mientras tenga subcategorias.",
        failedLoad: "No se pudieron cargar las categorias",
        failedCreate: "No se pudo crear la categoria",
        failedUpdate: "No se pudo actualizar la categoria",
        failedDelete: "No se pudo eliminar la categoria",
        deleteBlockedByTransactions:
          "No puedes eliminar esta categoria porque tiene transacciones asociadas. Primero elimina esas transacciones o cambialas a otra categoria.",
        ofTotal: (visible: number, total: number) => `(${visible} de ${total})`,
        pageOf: (page: number, total: number) => `Pagina ${page} de ${total}`,
        showingOfTotal: (visible: number, total: number) =>
          `Mostrando ${visible} de ${total}`,
        pageSizeLabel: (count: number) => `${count} por pagina`,
        previousPage: "Anterior",
        nextPage: "Siguiente",
        validations: {
          nameRequired: "El nombre es obligatorio",
        },
      },
      transactions: {
        title: "Transacciones",
        subtitle: "Haz seguimiento de tus ingresos y gastos.",
        newCardTitle: "Nueva transaccion",
        newCardDescription: "Registra un ingreso o un gasto.",
        addTransaction: "Agregar transaccion",
        category: "Categoria",
        parentCategory: "Grupo",
        amount: "Monto",
        currency: "Moneda",
        dateTime: "Fecha y hora",
        descriptionOptional: "Descripcion (opcional)",
        categoryPlaceholder: "Selecciona categoria",
        amountPlaceholder: "Ej: 50000",
        currencyPlaceholder: "COP",
        create: "Crear transaccion",
        creating: "Creando...",
        time: "Hora",
        filters: "Filtros",
        recentView: "Recientes",
        historyView: "Historial",
        recentListTitle: "Movimientos recientes",
        historyListTitle: "Historial completo",
        quickRangeToday: "Hoy",
        quickRangeLast7: "7 dias",
        quickRangeThisMonth: "Este mes",
        desktopView: "PC",
        mobileView: "Movil",
        moreFilters: "Mas filtros",
        summaryTransactions: "Movimientos",
        summaryIncome: "Ingresos",
        summaryExpense: "Gastos",
        summaryBalance: "Balance",
        summaryCategories: "Categorias activas",
        startDate: "Fecha inicial",
        endDate: "Fecha final",
        listTitle: "Transacciones",
        loading: "Cargando...",
        empty: "No se encontraron transacciones.",
        type: "Tipo",
        today: "Hoy",
        yesterday: "Ayer",
        pageOf: (page: number, total: number) => `Pagina ${page} de ${total}`,
        showingOfTotal: (visible: number, total: number) =>
          `Mostrando ${visible} de ${total}`,
        pageSizeLabel: (count: number) => `${count} por pagina`,
        previousPage: "Anterior",
        nextPage: "Siguiente",
        editTitle: "Editar transaccion",
        save: "Guardar cambios",
        saving: "Guardando...",
        deleteTitle: "Eliminar transaccion?",
        deleteDescription: (
          amount: string,
          description?: string,
        ) =>
          `Seguro que quieres eliminar esta transaccion de ${amount}${description ? ` - \"${description}\"` : ""}? Esta accion no se puede deshacer.`,
        created: "Transaccion creada",
        updated: "Transaccion actualizada",
        deleted: "Transaccion eliminada",
        failedLoad: "No se pudieron cargar las transacciones",
        failedCreate: "No se pudo crear la transaccion",
        failedUpdate: "No se pudo actualizar la transaccion",
        failedDelete: "No se pudo eliminar la transaccion",
        validations: {
          categoryRequired: "La categoria es obligatoria",
          amountRequired: "El monto es obligatorio",
          amountInvalid: "El monto solo puede contener numeros",
          currencyRequired: "La moneda es obligatoria",
          dateRequired: "La fecha es obligatoria",
        },
      },
      profile: {
        title: "Perfil",
        subtitle: "Administra la informacion de tu cuenta.",
        preferencesTitle: "Preferencias",
        preferencesDescription:
          "Configura idioma y apariencia de la aplicacion.",
        languageLabel: "Idioma",
        appearanceLabel: "Apariencia",
        languageEs: "Espanol",
        languageEn: "Ingles",
        themeSystem: "Sistema",
        themeLight: "Claro",
        themeDark: "Oscuro",
        infoCardTitle: "Informacion de la cuenta",
        infoCardDescription:
          "Tu nombre se puede editar y se guarda automaticamente.",
        fullName: "Nombre completo",
        fullNamePlaceholder: "Tu nombre",
        email: "Correo",
        memberSince: "Miembro desde",
        saving: "Guardando...",
        saved: "Guardado",
        dangerTitle: "Zona de peligro",
        dangerDescription:
          "Elimina permanentemente tu cuenta y todos los datos asociados.",
        deleteAccount: "Eliminar cuenta",
        confirmDeleteTitle: "Eliminar cuenta?",
        confirmDeleteDescription:
          "Esta accion es permanente. Tu perfil, transacciones y categorias se eliminaran y no se podran recuperar.",
        confirmDeleteButton: "Si, eliminar mi cuenta",
        deleting: "Eliminando...",
        deleted: "Cuenta eliminada",
        failedSaveName: "No se pudo guardar el nombre",
        failedDeleteAccount: "No se pudo eliminar la cuenta",
        dateLocale: "es-CO",
      },
    },
  },
  en: {
    metadata: {
      title: mainPageContent.en.seo.title,
      description: mainPageContent.en.seo.description,
      htmlLang: "en",
    },
    common: {
      loading: "Loading...",
      unexpectedError: "Unexpected error",
      mobileTableScrollHint: "Swipe to view more columns.",
      none: "None",
      all: "All",
      clearFilters: "Clear filters",
      refresh: "Refresh",
      cancel: "Cancel",
      saveChanges: "Save changes",
      edit: "Edit",
      delete: "Delete",
      actions: "Actions",
      direction: "Direction",
      category: "Category",
      date: "Date",
      amount: "Amount",
      currency: "Currency",
      description: "Description",
      dash: "-",
      income: "Income",
      expense: "Expense",
    },
    appLayout: {
      mobileMenuTitle: "Menu",
      mobileMenuDescription: "Navigate your dashboard and manage your session.",
      nav: {
        balance: "Balance",
        transactions: "Transactions",
        categories: "Categories",
        profile: "Profile",
      },
      signOut: "Sign out",
    },
    auth: {
      login: {
        title: "Sign in",
        email: "Email",
        password: "Password",
        submit: "Sign in",
        submitting: "Signing in...",
        google: "Continue with Google",
        googleSubmitting: "Redirecting to Google...",
        orContinueWithEmail: "or continue with email",
        noAccount: "Don't have an account?",
        register: "Register",
        notRegistered: "User is not registered.",
        validations: {
          invalidEmail: "Invalid email",
          passwordRequired: "Password required",
        },
        successToast: "Signed in successfully",
      },
      register: {
        title: "Create account",
        name: "Name",
        email: "Email",
        password: "Password",
        confirmPassword: "Confirm password",
        submit: "Create account",
        submitting: "Creating account...",
        google: "Sign up with Google",
        googleSubmitting: "Redirecting to Google...",
        orContinueWithEmail: "or create your account with email",
        hasAccount: "Already have an account?",
        signIn: "Sign in",
        validations: {
          nameRequired: "Name is required",
          invalidEmail: "Invalid email",
          passwordMin: "Password must be at least 8 characters",
          confirmRequired: "Please confirm your password",
          passwordsDontMatch: "Passwords don't match",
        },
        successToast: "Account created successfully.",
        profileCreatedToast: "User profile created successfully.",
      },
    },
    pages: {
      main: mainPageContent.en,
      balance: {
        title: "Balance",
        subtitle: "Financial summary for the selected month and full history.",
        heading: (monthLabel: string) => `Financial summary - ${monthLabel}`,
        monthLabel: "Month",
        latestMonthHint:
          "Without a filter, the latest month with activity is shown.",
        currentCardDescription:
          "Consolidated view of income, expenses, and balance.",
        onboardingTitle: "Get started with your balance",
        onboardingDescription:
          "To see results here, first create a category and then record a transaction.",
        onboardingCategoryStepTitle: "Create a category",
        onboardingCategoryStepDescription:
          "Organize your income or expenses before recording transactions.",
        onboardingTransactionStepTitle: "Record a transaction",
        onboardingTransactionStepDescription:
          "Add your first movement so the balance can start calculating.",
        onboardingCompleted: "Completed",
        onboardingPending: "Pending",
        onboardingCategoryPromptTitle: "Your first step",
        onboardingCategoryPromptDescription:
          "You do not have categories yet. Create one to start organizing your activity.",
        onboardingTransactionPromptTitle: "Next step",
        onboardingTransactionPromptDescription:
          "Your categories are ready. Now record your first transaction to see your balance.",
        historyTitle: "Monthly balance",
        historyDescription: "Every month with recorded activity.",
        noHistory: "There is no activity yet to calculate the balance.",
        selectedMonthEmpty: "There is no activity in the selected month.",
      },
      categories: {
        title: "Categories",
        subtitle:
          "Organize your transactions by income and expense categories.",
        newCardTitle: "New category",
        newCardDescription: "Add a category to group your transactions.",
        name: "Name",
        direction: "Direction",
        parentOptional: "Group into (optional)",
        parentHelpTitle: "What is this for?",
        parentHelpDescription:
          "If you choose a group, this category becomes a subcategory. Use it to organize where your money went or where it came from, for example: Home > Groceries.",
        namePlaceholder: "e.g. Groceries",
        addCategory: "Add category",
        create: "Create category",
        creating: "Creating...",
        filters: "Filters",
        listTitle: "Categories",
        groupedView: "Grouped",
        allView: "All",
        uncategorizedGroup: "No group",
        subcategoryLabel: "Subcategory",
        unknownParent: "Unknown group",
        subcategoriesCount: (count: number) => `${count} subcategories`,
        categoriesCount: (count: number) => `${count} categories`,
        loading: "Loading...",
        empty: "No categories found.",
        editTitle: "Edit category",
        save: "Save changes",
        saving: "Saving...",
        deleteTitle: "Delete category?",
        deleteDescription: (name: string) =>
          `Are you sure you want to delete \"${name}\"? This action cannot be undone.`,
        deleted: "Category deleted",
        created: "Category created",
        updated: "Category updated",
        duplicateCategory: (name: string) =>
          `Your category ${name} already exists`,
        groupCannotBecomeSubcategory:
          "You cannot assign a group because this category already acts as a group.",
        groupMustBeTopLevel:
          "You can only group inside a top-level category.",
        groupMustMatchDirection:
          "The group must have the same direction as the category.",
        groupDirectionCannotChange:
          "You cannot change a group's direction while it has subcategories.",
        failedLoad: "Failed to load categories",
        failedCreate: "Failed to create category",
        failedUpdate: "Failed to update category",
        failedDelete: "Failed to delete category",
        deleteBlockedByTransactions:
          "You cannot delete this category because it has related transactions. First delete those transactions or move them to another category.",
        ofTotal: (visible: number, total: number) => `(${visible} of ${total})`,
        pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
        showingOfTotal: (visible: number, total: number) =>
          `Showing ${visible} of ${total}`,
        pageSizeLabel: (count: number) => `${count} per page`,
        previousPage: "Previous",
        nextPage: "Next",
        validations: {
          nameRequired: "Name is required",
        },
      },
      transactions: {
        title: "Transactions",
        subtitle: "Track your income and expenses.",
        newCardTitle: "New transaction",
        newCardDescription: "Record a new income or expense.",
        addTransaction: "Add transaction",
        category: "Category",
        parentCategory: "Group",
        amount: "Amount",
        currency: "Currency",
        dateTime: "Date & time",
        descriptionOptional: "Description (optional)",
        categoryPlaceholder: "Select category",
        amountPlaceholder: "e.g. 50000",
        currencyPlaceholder: "COP",
        create: "Create transaction",
        creating: "Creating...",
        time: "Time",
        filters: "Filters",
        recentView: "Recent",
        historyView: "History",
        recentListTitle: "Recent activity",
        historyListTitle: "Full history",
        quickRangeToday: "Today",
        quickRangeLast7: "7 days",
        quickRangeThisMonth: "This month",
        desktopView: "Desktop",
        mobileView: "Mobile",
        moreFilters: "More filters",
        summaryTransactions: "Transactions",
        summaryIncome: "Income",
        summaryExpense: "Expenses",
        summaryBalance: "Balance",
        summaryCategories: "Active categories",
        startDate: "Start date",
        endDate: "End date",
        listTitle: "Transactions",
        loading: "Loading...",
        empty: "No transactions found.",
        type: "Type",
        today: "Today",
        yesterday: "Yesterday",
        pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
        showingOfTotal: (visible: number, total: number) =>
          `Showing ${visible} of ${total}`,
        pageSizeLabel: (count: number) => `${count} per page`,
        previousPage: "Previous",
        nextPage: "Next",
        editTitle: "Edit transaction",
        save: "Save changes",
        saving: "Saving...",
        deleteTitle: "Delete transaction?",
        deleteDescription: (
          amount: string,
          description?: string,
        ) =>
          `Are you sure you want to delete this transaction of ${amount}${description ? ` - \"${description}\"` : ""}? This action cannot be undone.`,
        created: "Transaction created",
        updated: "Transaction updated",
        deleted: "Transaction deleted",
        failedLoad: "Failed to load transactions",
        failedCreate: "Failed to create transaction",
        failedUpdate: "Failed to update transaction",
        failedDelete: "Failed to delete transaction",
        validations: {
          categoryRequired: "Category is required",
          amountRequired: "Amount is required",
          amountInvalid: "Amount can only contain numbers",
          currencyRequired: "Currency is required",
          dateRequired: "Date is required",
        },
      },
      profile: {
        title: "Profile",
        subtitle: "Manage your account information.",
        preferencesTitle: "Preferences",
        preferencesDescription: "Configure app language and appearance.",
        languageLabel: "Language",
        appearanceLabel: "Appearance",
        languageEs: "Spanish",
        languageEn: "English",
        themeSystem: "System",
        themeLight: "Light",
        themeDark: "Dark",
        infoCardTitle: "Account information",
        infoCardDescription: "Your name is editable and saves automatically.",
        fullName: "Full name",
        fullNamePlaceholder: "Your name",
        email: "Email",
        memberSince: "Member since",
        saving: "Saving...",
        saved: "Saved",
        dangerTitle: "Danger zone",
        dangerDescription:
          "Permanently delete your account and all associated data.",
        deleteAccount: "Delete account",
        confirmDeleteTitle: "Delete account?",
        confirmDeleteDescription:
          "This action is permanent. Your profile, transactions, and categories will be deleted and cannot be recovered.",
        confirmDeleteButton: "Yes, delete my account",
        deleting: "Deleting...",
        deleted: "Account deleted",
        failedSaveName: "Failed to save name",
        failedDeleteAccount: "Failed to delete account",
        dateLocale: "en-US",
      },
    },
  },
} as const;

export type SiteText = (typeof siteTexts)[SiteLocale];

export function getSiteText(locale: SiteLocale = defaultSiteLocale): SiteText {
  return siteTexts[locale] ?? siteTexts[defaultSiteLocale];
}
